"use strict";

module.exports = {
  ...require("./auth"),
  ...require("./common"),
  ...require("./error"),
  ...require("./http"),
  ...require("./sendGrid"),
  ...require("./model"),
  ...require("./s3"),
  ...require("./token"),
  ...require("./user"),
  ...require("./customer.js"),
  ...require("./otpPurposes"),
  ...require("./currency.js"),
  ...require("./transaction_sources"),
  ...require("./customer_types"),
  ...require("./merchant"),
  ...require("./ticket"),
  ...require("./category"),
  ...require("./notification"),
  ...require("./faq"),
  ...require("./rating"),
  ...require("./slider"),
  ...require("./language"),
  ...require("./roles"),
  ...require("./storeLoyalty"),
  ...require("./membershipClaim.js"),
  ...require("./foodics"),
  ...require("./order"),
  ...require("./cartRule"),
  ...require("./vibeCategory"),
  ...require("./pushNotification"),
  ...require("./settings"),
  ...require("./holding_schema"),
  ...require("./activity_log"),
  ...require('./webhook')
};
