const LOG_TYPE = {
  ERROR: "Error",
  WARNING: "Warning",
  INFO: "Info",
  MESSAGE: "Message",
};

const LOG_PLATFORM = {
  MOBILE_APP: "MOBILE_APP",
  PUBLIC_API: "PUBLIC_API",
  VENDOR_APP: "VENDOR_APP",
  ADMIN_CONSOLE: "ADMIN_CONSOLE",
  MERCHANT_CONSOLE: "MERCHANT_CONSOLE",
};

module.exports = {
  LOG_TYPE,
  LOG_PLATFORM,
};
